import { requireAppUser } from "@/lib/auth";
import { WorkspaceHeader } from "@/components/workspace-header";
import { SettingsNav } from "@/components/settings-nav";
import { updateAiSettings, updateChannelSettings, updateNotificationSettings, updateProfileSettings, updateSchedulingSettings } from "./actions";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ tab?: string; saved?: string; error?: string }> }) {
  const params = await searchParams;
  const tab = params.tab ?? "ai";
  const { supabase, user, profile } = await requireAppUser();
  const { data: settings } = await supabase.from("profiles").select("phone,ai_confidence_threshold,ai_auto_execute,ai_log_decisions,scheduling_duration,scheduling_buffer_min,scheduling_reschedule_limit,working_hours_start,working_hours_end,notif_new_reply,notif_confirmed,notif_reminders,notif_weekly_digest,email_from_name,email_from_address,email_reply_to,email_signature").eq("id", user.id).single();

  return <div className="workspace-page">
    <WorkspaceHeader title="Settings" subtitle="Configure how Schela sounds, schedules, and escalates"/>
    {params.saved ? <div className="alert alert-success">Settings saved.</div> : null}
    {params.error ? <div className="alert alert-error">{params.error}</div> : null}
    <div className="settings-workspace">
      <SettingsNav active={tab}/>
      <section className="workspace-card settings-content">
        {tab === "profile" ? <form action={updateProfileSettings} className="settings-form"><SettingsTitle title="Profile" copy="Your recruiter identity inside Schela."/><Field label="Full name"><input name="fullName" defaultValue={profile.full_name}/></Field><Field label="Email"><input disabled value={profile.email}/></Field><Field label="Phone"><input name="phone" defaultValue={settings?.phone ?? ""} placeholder="Optional"/></Field><Save/></form> : null}
        {tab === "ai" ? <form action={updateAiSettings} className="settings-form"><SettingsTitle title="AI Preferences" copy="Controls how Schela talks to candidates and when it hands off to you."/><Field label="Confidence threshold" hint="Below this, Schela asks for clarification or escalates instead of guessing."><div className="threshold-control"><input name="threshold" type="range" min="0" max="100" step="1" defaultValue={settings?.ai_confidence_threshold ?? 65}/><b>{((settings?.ai_confidence_threshold ?? 65)/100).toFixed(2)}</b></div></Field><Field label="Sensitive topics that always escalate"><div className="readonly-setting">Compensation and Visa/sponsorship always escalate. Other hiring questions follow the AI decision and confidence policy.</div></Field><Toggle name="autoExecute" label="Fully automated replies" copy="Schela can reply immediately when the decision is above your confidence threshold." defaultChecked={settings?.ai_auto_execute ?? true}/><Toggle name="logDecisions" label="AI decision logging" copy="Keep the auditable decision trail used for debugging and analytics." defaultChecked={settings?.ai_log_decisions ?? true}/><Save/></form> : null}
        {tab === "scheduling" ? <form action={updateSchedulingSettings} className="settings-form"><SettingsTitle title="Scheduling" copy="Default timing rules Schela uses when coordinating interviews."/><div className="settings-grid"><Field label="Default duration"><select name="duration" defaultValue={settings?.scheduling_duration ?? "45m"}><option value="30m">30 minutes</option><option value="45m">45 minutes</option><option value="60m">60 minutes</option><option value="90m">90 minutes</option></select></Field><Field label="Buffer between interviews"><input name="buffer" type="number" min="0" max="180" defaultValue={settings?.scheduling_buffer_min ?? 15}/></Field><Field label="Reschedule limit"><input name="rescheduleLimit" type="number" min="0" max="20" defaultValue={settings?.scheduling_reschedule_limit ?? 3}/></Field><Field label="Working day starts"><input name="start" type="time" defaultValue={settings?.working_hours_start ?? "09:00"}/></Field><Field label="Working day ends"><input name="end" type="time" defaultValue={settings?.working_hours_end ?? "18:00"}/></Field></div><Save/></form> : null}
        {tab === "notifications" ? <form action={updateNotificationSettings} className="settings-form"><SettingsTitle title="Notifications" copy="Choose which coordination events should get your attention."/><Toggle name="newReply" label="New candidate replies" copy="Notify me when a candidate sends a new message." defaultChecked={settings?.notif_new_reply ?? true}/><Toggle name="confirmed" label="Interview confirmations" copy="Notify me when a candidate books or confirms a time." defaultChecked={settings?.notif_confirmed ?? true}/><Toggle name="reminders" label="Reminder activity" copy="Notify me about scheduled interview reminders." defaultChecked={settings?.notif_reminders ?? true}/><Toggle name="digest" label="Weekly digest" copy="Receive a weekly summary of coordination activity." defaultChecked={settings?.notif_weekly_digest ?? false}/><Save/></form> : null}
        {tab === "channels" ? <form action={updateChannelSettings} className="settings-form"><SettingsTitle title="Channels" copy="Email identity used by your Schela workspace. Provider credentials remain server-side."/><div className="settings-grid"><Field label="Email from name"><input name="fromName" defaultValue={settings?.email_from_name ?? ""} placeholder="Schela Recruiting"/></Field><Field label="Email from address"><input name="fromAddress" type="email" defaultValue={settings?.email_from_address ?? ""} placeholder="interviews@company.com"/></Field><Field label="Reply-to"><input name="replyTo" type="email" defaultValue={settings?.email_reply_to ?? ""} placeholder="replies@company.com"/></Field></div><Field label="Signature"><textarea name="signature" rows={4} defaultValue={settings?.email_signature ?? ""}/></Field><Save/></form> : null}
        {tab === "billing" ? <div className="settings-form"><SettingsTitle title="Billing" copy="Billing is not connected to this Schela build yet."/><div className="readonly-setting">No billing provider or subscription table is wired into the current production core, so this screen intentionally does not show fake plan data.</div></div> : null}
      </section>
    </div>
  </div>;
}

function SettingsTitle({ title, copy }: { title:string; copy:string }) { return <div className="settings-title"><h2>{title}</h2><p>{copy}</p></div>; }
function Field({ label, hint, children }: { label:string; hint?:string; children:React.ReactNode }) { return <label className="settings-field"><span>{label}</span>{children}{hint ? <small>{hint}</small> : null}</label>; }
function Toggle({ name, label, copy, defaultChecked }: { name:string; label:string; copy:string; defaultChecked:boolean }) { return <label className="setting-toggle"><span><b>{label}</b><small>{copy}</small></span><input type="checkbox" name={name} defaultChecked={defaultChecked}/><i/></label>; }
function Save() { return <button className="button button-primary settings-save" type="submit">Save changes</button>; }
